version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=912072
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: f1_results_api
    image: afdev9988/f1-results-api:0.0.1
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: f1_user
      DB_PASSWORD: a912072
      DB_NAME: f1_db
    links:
      - db
    volumes:
      - /:/src
volumes:
  db:
    driver: local