version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=912072
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: f1_results_api
    image: afdev9988/f1-results-api:0.0.1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/f1_db
      - SPRING_DATASOURCE_USERNAME=f1_user
      - SPRING_DATASOURCE_PASSWORD=a912072
    links:
      - db
    volumes:
      - /:/src
volumes:
  db:
    driver: local