name: Integration tests

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk-alpine
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: f1_user
          POSTGRES_PASSWORD: a912072
          POSTGRES_DB: f1_db1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Prepare Maven
        run: chmod +x mvnw
      - name: Launch tests
        run: ./mvnw install -D spring.profiles.active=test
        env:
          POSTGRES_HOST: postgres
      - name: Launch tests
        run: ls /__w/F1-Results-API/F1-Results-API/target/site/jacoco/
        
      - name: Save Coverage To Environment Variable
        run: |
          echo "TOTAL_COVERAGE=${{ steps.jacoco.outputs.coverage-overall }}" >> $GITHUB_ENV
          echo "CHANGED_FILES_COVERAGE=${{ steps.jacoco.outputs.coverage-changed-files }}" >> $GITHUB_ENV

      - name: Print & Check Coverage Info
        run: |
          import os
          import sys
          print("Total Coverage: " + str(os.environ["TOTAL_COVERAGE"]))
          print("Changed Files Coverage: " + str(os.environ["CHANGED_FILES_COVERAGE"]))
          if float(os.environ["TOTAL_COVERAGE"]) < 80 or float(os.environ["CHANGED_FILES_COVERAGE"]) < 80:
            print("Insufficient Coverage!")
            sys.exit(-1) # Cause Status Check Failure due to noncompliant coverage
          sys.exit(0)
        shell: python
        
      - name: Generate JaCoCo Badges
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: /__w/F1-Results-API/F1-Results-API/target/site/jacoco/jacoco.csv
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg
          coverage-label: coverage
          branches-label: branches
      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Angel Flores'
            git config --global user.email 'afv9988@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
