name: Integration tests

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk-alpine
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: f1_user
          POSTGRES_PASSWORD: a912072
          POSTGRES_DB: f1_db1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Prepare Maven
        run: chmod +x mvnw
      - name: Launch tests
        run: ./mvnw install -D spring.profiles.active=test
        env:
          POSTGRES_HOST: postgres
      - name: Generate JaCoCo Badges
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
