name: Integration tests

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: openjdk:8-jdk-alpine
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: f1_user
          POSTGRES_PASSWORD: a912072
          POSTGRES_DB: f1_db1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Prepare Maven
        run: chmod +x mvnw
      - name: Launch tests with Maven
        run: ./mvnw clean install
        env:
          POSTGRES_HOST: postgres
