name: Integration Tests Embedded

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: bitnami/git:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Prepare Maven
        run: chmod +x mvnw
      - name: Launch tests
        run: ./mvnw install -D spring.profiles.active=embedded
      - name: Generate JaCoCo Badges
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Prepare git
        run: git config --global --add safe.directory '*'
      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'
